### PR TITLE
Added new service to create rigid bodies

### PR DESCRIPTION
**Pull request by Juancams**
Service to create new rigid bodies with various markers. The parent link must be specified, from which it will take the orientation. The position will be the calculation of the centroid of all the added markers.

### CODE REVIEW

**Comment by aaggj** [comment]
LGTM, thank you :), I have created it in srv_rolling branch.

**Comment by fmrico** [comment]
Was this included in the REP? Do you think we should include it?

**Comment by Juancams** [comment]
Hi @fmrico 

I don't know if the REP is for humble, jazzy, rolling or all of them, but this is something that requires the current version of the gazebo plugin in humble, which I don't know if it will be included either. In any case, it can be moved to another branch.

**Comment by aaggj** [comment]
Hi, this is one thing We would like to discuss with you. Now, is not included in the rep.

**Pull request merged**
